name: Publish

on:
  push:
    branches: main
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push master
        id: docker_build_master
        uses: docker/build-push-action@v2
        if: ${{ github.event.release.tag_name == '' }}
        with:
          push: true
          tags: ghcr.io/snorwin/haproxy-wirh-reload:latest
          platforms: linux/amd64